Feature/more emojis
start-again/spookyBot pull request #32
Opened 2020-10-04 10:53 UTC by Mr1BitL8r

Added more emojis for the English template and introduced the idea of using unique names that match the names used on https://emojipedia.org/halloween/ so that it is easier to identify, add and later also add more translations.

2020-10-04 11:10 UTC, tmetten commented
Whoa! 😮

2020-10-05 18:04 UTC, illusi0nary requested changes

2020-10-05 18:04 UTC, illusi0nary commented on lang/en.js
> +      emoji: '🫀',
This seems to be correct - is that only me ? 
I just see 🫀 - that might cause problems?

2020-10-05 18:04 UTC, illusi0nary commented on lang/en.js
> +      emoji: '🥸',
Same here it is only showing 🫀

2020-10-05 21:19 UTC, Mr1BitL8r commented on lang/en.js
> +      emoji: '🥸',
Thanks for the hint. Some emojis are too new so I changed them into comments and added the hint that they arrive later this year wit Unicode/Emoji 13.0, e.g. for Android 11.
The "Performing Arts" one actually was a copy-paste issue and should be fixed now. :)

2020-10-05 21:20 UTC, Mr1BitL8r commented on lang/en.js
> +      emoji: '🫀',
Thanks for the hint. Some emojis are too new (e.g. "headstone" as well) so I changed them into comments and added the hint that they arrive later this year wit Unicode/Emoji 13.0, e.g. for Android 11.

2020-10-06 09:25 UTC, illusi0nary approved these changes
All good :-)

2020-10-06 18:46 UTC, LucasCtrl approved these changes
I'm going to merge the changes but I'll delete the unique ID part and the comment one.
I the future, we are maybe going to change the file structure

2020-10-06 18:46 UTC, merged